### ISSUE TITLE
fp16 preprocessing

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#10]
7.1 has fp32 <-> int8 preprocessing conversion as untimed. We would like to add fp16 also.

**Comment by tjablin** [comment]
SGTM

**Comment by christ1ne** [comment]
change 'May quantize image data from fp32 to int8 and between signed and unsigned' to 'may convert among all the whitelisted data formats' @jveejay

**Comment by christ1ne** [comment]
PR merged.
