### ISSUE TITLE
RND seeds change shall be in the check list of valid loadgen commit list in the questionaire

### ISSUE THREAD

**Issue by aaronzhongii** [mlperf/inference_policies#104]
in our details log
7dc0950cb7cf5201a72e80c24bb9c34ebdfe4fab Add the RNG Seeds
61220457dec221ed1984c62bd9d382698bd71bc6 loadgen: re-apply fix for msvc (#459)
5684c11e3987b614aae830390fa0e92f56b7e800 Update the broken txt url link (#456)
55c0ea4e772634107f3e67a6d0da61e6a2ca390d https://github.com/mlperf/inference/issues/450 logging per-sample info regardless of scenario (#454)
d31c18fbd9854a4f1c489ca1bc4cd818e48f2bc5 Adding a flag to accuracy-coco script which fixes issue with preprocessing that removes 48 empty images (#453)
1d0e06e54a7d763cf228bdfd8b1e987976e4222f Implement LogSettings::enable_trace (#466)
...

but int he questionaire, only
- [ ] 61220457dec221ed1984c62bd9d382698bd71bc6
- [ ] 5684c11e3987b614aae830390fa0e92f56b7e800
- [ ] 55c0ea4e772634107f3e67a6d0da61e6a2ca390d
- [ ] d31c18fbd9854a4f1c489ca1bc4cd818e48f2bc5
- [ ] 1d0e06e54a7d763cf228bdfd8b1e987976e4222f

**Comment by tjablin** [comment]
@guschmue @briandersn Can you update this list?

**Comment by aaronzhongii** [comment]
tom,
looks like you withdraw the change? so we need to update mlperf.conf for the rand seed? i have to rerun everything, this sucks.

**Comment by tjablin** [comment]
What change?

**Comment by aaronzhongii** [comment]
so I sync the inference to tip and try to cherry pick your rnd seed change again and found it's closed, then I found Anton proposed to update mlperf.conf to include the rnd seeds. So I guess this is the new decision about how we should set the rnd seeds? anyway, I am rerunning all the tests now.

**Comment by tjablin** [comment]
Yeah. Anton's configuration change is better than hardcoding the seed. Particularly, since NVIDIA's audits will require re-running with a different seed.

**Comment by aaronzhongii** [comment]
sure, just I need to rerun all the tests (so that the detail log can be perfect), doing it now.

**Comment by briandersn** [comment]
I was just doing an audit of the recent commits that don't have a SHA1 in the submission_checklist.md

There are a lot. Only one touches loadgen. Rather than add a bunch of SHA1's to the checklist, I think we should rely on the existing "Other" option in the checklist and allow folks to specify any commit that is on top of the ones in the existing list.

**Comment by aaronzhongii** [comment]
All the latest changes, only one change touch loadgen directory, as in https://github.com/mlperf/inference/commits/master/loadgen

Though detailed log includes all the changes, but i still check the 6122045 box in self checker. I don't think there is any problem, unless d381431 is also used in your submission.

Aaron


------------------------------------------------------------------

**Comment by christ1ne** [comment]
We will include random seed in the next round of the checklist update for inference v0.6. Please re-open if you don't see it there.
