### ISSUE TITLE
about correct number of times of scenario in the questionaire

### ISSUE THREAD

**Issue by aaronzhongii** [mlperf/inference_policies#105]
For each SUT and scenario, is the submission run the correct number of
times for the relevant scenario? (check one)
- [ ] Yes (Accuracy 1x Performance 1x Single-Stream, Multi-Stream,
Offline)
- [ ] Yes (Accuracy 1x Performance **1x** Server)

should be 5x instead of 1x for Server right?

**Comment by tjablin** [comment]
Yikes! Nice catch will fix.

**Comment by tjablin** [comment]
Resolved in be618cfd9b03928b79edd27ca0681e0cac9c231a.
