### ISSUE TITLE
Clarify server runs and scores?

### ISSUE THREAD

**Issue by TheKanter** [mlperf/inference_policies#106]
At the end of section 3 of the rules, we define the number of runs needed for a valid submission:
5 for server
1 for all other scenarios

We do not specify how the five runs in server are used to compute a score (and if we agreed I don't remember), e.g.,

1. Arithmetic average
2. Drop high and low, average remainder
3. Median
4. Lowest

I would recommend 1, but we should discuss.

**Comment by tjablin** [comment]
> For a specific throughput value, queries are generated at that QPS using a Poisson distribution. LoadGen will use a binary search to find a candidate value. It will then verify stability by testing the value 5 times. If one run fails, it will reduce the value by a small delta then try again.

You have to meet or exceed your reported throughput in each of the five runs. In other words, the min of the five runs.

**Comment by tjablin** [comment]
Statistically, one in one hundred runs will be golden and one in one hundred will be leaden. If you have to run a sixth time and drop one run that's fine, but if you are running five hundred times and cherry picking the top five you should take a long hard look in the mirror.

**Comment by tjablin** [comment]
> A 99% confidence bound was somewhat arbitrarily selected. For systems with noisy latencies, it is possible to obtain better MLPerf results by cherry picking the best runs. Approximately 1 in 100 runs will be marginally better. Please don’t do this. It is very naughty and will make the MLPerf community feel sad.

**Comment by TheKanter** [comment]
Thanks.
