### ISSUE TITLE
Scenario table is inconsistent with FAQ for server

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#109]
For server scenario, the table clearly says that the metric is the Poisson parameter, but down in the FAQ (and IMHO easily overlooked) is that it's scheduled queries/second.

@tjablin which is correct? Can we fix the incorrect one?

**Comment by tjablin** [comment]
"Maximum Poisson throughput parameter supported" means the maximum throughput for queries generated by a Poisson process. "Scheduled samples per second" is the "Maximum Poisson throughput parameter supported." If you dig into the LoadGen, the calculation of "Scheduled samples per second" is slightly idiosyncratic, but I think it is fine for MLPerf Inference 0.5 and too late to change regardless. The important point is that when the LoadGen prints:

```
================================================
MLPerf Results Summary
================================================
SUT name : XXX
Scenario : Server
Mode     : Performance
Scheduled samples per second : YYY
Result is : VALID
  Performance constraints satisfied : Yes
  Min duration satisfied : Yes
  Min queries satisfied : Yes

================================================
Additional Stats
================================================
Completed samples per second    : ZZZ
```

That you report YYY and **not** ZZZ. If people post the wrong number, we'll fix it in review. YYY and ZZZ should not be **very** different.

**Comment by DilipSequeira** [comment]
Thanks. We'll use YYY.

But also, I should've been clearer - the distinction I was making was between the poisson parameter to the distribution (target mean frequency) and the issued QPS over the run (observed mean frequency.) The latter is expected to converge on the former, of course.

I suggest the natural meaning of the table is the first, and the FAQ gives the second.

Let's fix when we're not all scrambling.

**Comment by christ1ne** [comment]
we should be ok now as the submission checker reports the scores
