### ISSUE TITLE
clarify the number of outstanding queries allowed

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#11]
duplicating:
https://github.com/mlperf/training_policies/issues/217

**Comment by christ1ne** [comment]
WG: we agree with this. @briandersn can you add to your readme?

**Comment by christ1ne** [comment]
@briandersn just a reminder.

**Comment by tjablin** [comment]
Friendly ping?

**Comment by briandersn** [comment]
This was mostly done already, but will be complete with https://github.com/mlperf/inference/pull/426, which documents the server scenario more explicitly in the loadgen documentation.

I see that this has the "WG rec no rule update" label. Does that mean we don't need to clarify the policy doc as well?

**Comment by christ1ne** [comment]
no rule update needed. Code already in.
