### ISSUE TITLE
Clarify GNMT preprocessing

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#111]
Issue #72 attempts to do this, but the discussion there is not obviously pertinent to the decision that was reached, and the decision itself is not clear.

We need either to clearly allow the mapping from token substrings to embedding indices to be untimed, or state clearly that it is timed.

**Comment by tjablin** [comment]
For MLPerf Inference Next, I'd like to make all pre-processing timed. What do you think? Also, if untimed pre-processing is allowed in MLPerf Inference Next, do you think tokenization ought to be timed or untimed?

**Comment by tjablin** [comment]
To be clear, I think that even JPEG decode ought to be timed to reward people with hardware JPEG decoders.

**Comment by DilipSequeira** [comment]
In Next, I'd like to see much stronger correspondence between the benchmark/scenario combinations and the use cases. 

For GNMT, I think tokenization should be timed. JPEG decode is something we might choose to vary by scenario, because some are intended for input from camera.

**Comment by tjablin** [comment]
Maybe allow untimed preprocessing in Single- and Multi-Stream and disallow in Server and Offline?

**Comment by DilipSequeira** [comment]
I think that's the right division.

**Comment by christ1ne** [comment]
I suggest we close this as GNMT is not in the next round.
