### ISSUE TITLE
Time pre-processing, JPEG decoding?

### ISSUE THREAD

**Issue by TheKanter** [mlperf/inference_policies#115]
Request to re-open whether we should we change the rules about JPEG decoding and other pre-processing steps?

Current rules: Use bitmaps, don't time JPEG decode, sample-independent pre-processing is untimed. See https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#pre-and-post-processing

Xiaoqi Cao says: To test end-to-end (E2E) duration is more realistic. To enhance the performance on this promotes the use experience in real use cases.

**Comment by christ1ne** [comment]
dup of #184
