### ISSUE TITLE
Request for models for devices smaller than smartphones

### ISSUE THREAD

**Issue by TheKanter** [mlperf/inference_policies#117]
Comment from MLPerf Inference v0.7 wishlist document.

Note that the TinyML group seems to be providing this, so perhaps we can close?

Xiaoqi Cao says: seperate inference to cloud, edge-server and edge sides. It is closer to realistic industrial applications.

**Comment by christ1ne** [comment]
any action needed? Otherwise we should close this.

**Comment by TheKanter** [comment]
The TinyML group, lead by VJ is handling this. For further questions, contact @jveejay
