### ISSUE TITLE
Complex multi-model benchmarks

### ISSUE THREAD

**Issue by TheKanter** [mlperf/inference_policies#120]
Comment from MLPerf Inference v0.7 wishlist document:

Request for multiple dependent and independent inferences per query (eg. image-to-text-to-voice, voice-to-text-to-translate-to-voice).

**Comment by christ1ne** [comment]
The WG agreed to consider a more detailed and concrete proposal if someone is willing to do the investigation. Please respond to this in 10 days if you'd like to champion this.

**Comment by christ1ne** [comment]
No one showed interest in a proposal so we will close this issue for now and re-open if needed.
