### ISSUE TITLE
Request for queries to arrive from network

### ISSUE THREAD

**Issue by TheKanter** [mlperf/inference_policies#121]
Comment from MLPerf Inference v0.7 wishlist document.

Currently queries start in DRAM, which simulates arrival from an I/O device (e.g., sensor or network).

Xiaoqi Cao says: It is more realistic.

David Kanter says: This will massively complicate an already complicated benchmark! Also, many queries come from system sensors, e.g., smartphone cameras. Network might be appropriate for cloud scenarios, but I am strongly opposed to the additional complexity and expense. It would also encourage people to use unrealistic networking configurations for benchmarking purposes.

**Comment by christ1ne** [comment]
The WG agreed that we need to have a concrete proposal including how to measure the updated performance with this change. If you'd like to champion this, please respond within 10 days.

**Comment by christ1ne** [comment]
No one showed interest in a proposal. We will close this for now and re-open if needed
