### ISSUE TITLE
Mobile division

### ISSUE THREAD

**Issue by TheKanter** [mlperf/inference_policies#122]
Comment from MLPerf Inference v0.7 wishlist document.

Request for mobile division and also a burst mode scenario, where N queries arrive simultaneously. It is implied that latency would be the metric.

DK thinks we can probably close as we have a mobile WG now!

**Comment by jveejay** [comment]
@christ1ne and @TheKanter can we create tags here for different groups who should answer the questions? for instance, this seems like a good thing that the mobile WG should focus on and come back with a decision. Could we create a mobile WG tag or something?

**Comment by christ1ne** [comment]
done. please check

**Comment by jveejay** [comment]
Thanks!
