### ISSUE TITLE
Reduce NMT beamwidth

### ISSUE THREAD

**Issue by TheKanter** [mlperf/inference_policies#124]
Comment from MLPerf Inference v0.7 wishlist document.

We found that NMT beam width (10) in v0.5 was greater than necessary to deliver the required accuracy (peak accuracy at 4, acceptable at 1 in BF16). However, several submitters had already started optimizing using the initial beam width. To be fair we required everyone to use the same beamwidth.

This suggestion would have us use a more sensible beam width given the accuracy and was largely agreed upon by participants. Need to determine reasonable beam width.

**Comment by christ1ne** [comment]
Let's put this on hold until we are sure GNMT stays.

**Comment by christ1ne** [comment]
suggest to close as GNMT is no longer in v0.7
