### ISSUE TITLE
Different implementations for different input sizes

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#128]
In the section on model equivalence, change this:

_Different implementations based on dynamically determined batch size_

to this

_Different implementations based on dynamically determined batch or input size_

The use cases are problems with variable input size (e.g. BERT, RNN-T, potentially DLRM) where the preferred implementation for small sizes may be different from that for large sizes.

**Comment by tjablin** [comment]
LGTM

**Comment by TheKanter** [comment]
Approved per 2020.07.28 WG meeting.
