### ISSUE TITLE
Placement of loadgen samples in accelerator memory

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#129]
NVIDIA is seeking approval to place the loadgen samples in accelerator memory. A production system using this capability would leverage NVIDIA's [GPUDirect](https://developer.nvidia.com/gpudirect) capability, in concert with the [DPDK](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9730-packet-processing-on-gpu-at-100gbe-line-rate.pdf) library.

To support this request, we propose changing this (in the section on loadgen operation):

"The trace generated by LoadGen must be stored in the non-HBM DRAM that most faithfully simulates queries arriving from the most logical source, which is usually the network or an I/O device such as a camera. It may be pinned. Submitters need prior approval for anything that is not DRAM."

to this:

"The trace generated by LoadGen must be stored in the DRAM that most faithfully simulates queries arriving from the most logical source, which is usually the network or an I/O device such as a camera. It may be pinned. 

Submitters seeking to use anything other than the DRAM attached to the processor on which loadgen is running must seek prior approval, and must provide with their submission sufficient system architecture details to show how the input activation bandwidth utilized by each benchmark/scenario combination can be delivered from the network or I/O device to that memory."

**Comment by tjablin** [comment]
A couple comments:

> the DRAM attached to the processor on which loadgen is running

In the future, I think there will be accelerators that will run the loadgen. Consider a system with a small ARM core and an accelerator sharing HBM and connected to a laptop by a USB interface. I would still want to consider the bandwidth of the USB interface when determining the maximum throughput of the system.

> from the network or I/O device to that memory.

There's a subtly here where I would like to confirm that there is enough IO bandwidth, but I don't care what NIC is actually installed. Consider a system with 128 GB/s of PCIe bandwidth with gigabit Ethernet.

**Comment by tjablin** [comment]
How about:

"The trace generated by LoadGen must be stored in the memory that most faithfully simulates queries arriving from the most logical source, which is usually the network, non-volatile storage, or I/O device such as a camera. It may be pinned.

Submitters must provide with their submission sufficient system architecture details to show how the input activation bandwidth utilized by each benchmark/scenario combination can be delivered from a network, non-volatile storage, or I/O device to that memory."

**Comment by DilipSequeira** [comment]
Thanks - LGTM.

**Comment by tjablin** [comment]
Are you confident this will work properly for SRAM only devices? Devices that enable DMAs from NICs  or SSDs to SRAMs?

**Comment by DilipSequeira** [comment]
I think our goal should be to ensure that the MLPerf rules are reasonably reflective of the system bottlenecks that would exist in production, but don't impose other bottlenecks. So if people have a NIC to their SRAM and a way to receive queries that will sustain their claimed performance, that's something the MLPerf rules should allow.

I haven't thought through all the possible abuses, but I think "most faithfully simulates" provides guidance you should only do things that make sense in production (e.g. bolting some otherwise inaccessible non-volatile storage onto an accelerator, and claiming that allows you to place queries in device memory, wouldn't work.)

**Comment by christ1ne** [comment]
This allows the some submitters to start the run with samples in the accelerator memory and allows building larger systems.  WG will come back to this issue next week.

**Comment by christ1ne** [comment]
@tjablin @DilipSequeira can you share the deployment use cases for this change proposal?

**Comment by DilipSequeira** [comment]
For NVIDIA... our GPUs have a capability called GPUDirect (https://developer.nvidia.com/gpudirect) which enables the CPU to schedule data transfer direct from network or storage to accelerator memory. The relevant production use case is to deliver query data directly to the accelerator for inference  (which would typically also involve some preprocessing, also running on the GPU), thereby avoiding system bottlenecks in DRAM or PCI-E bandwidth.

**Comment by TheKanter** [comment]
Closed pending Dilip's rule pull request.
