### ISSUE TITLE
Limit maximum length of offline run

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#132]
For the question:

_Q: Is it permissible to exceed both the minimum number of queries and minimum time duration in a valid test run?_

Change:

_A: Yes._

To:

_A: for single stream, server and multistream there is no limit on the time duration. Offline must use a single query, and the minimum time duration may be exceeded by at most 10%._

MLPerf should not support amortizing away large constant-time costs (e.g. loading a program onto an FPGA for a different sequence length in RNN-T or BERT) across an offline run which sorts an arbitrarily large dataset by sequence length.

**Comment by tjablin** [comment]
I think the Offline scenario is supposed to capture asymptotic performance. Moreover, the timer for offline doesn't start until the SUT indicates it is ready to receive the first query. A real offline job might run for hours or days, a 60 second run might not be long enough to capture typical behavior.
