### ISSUE TITLE
pre and post processing should be mathematically equivalent to the reference 

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#133]
Currently there is no mathematical equivalence rule to the pre and post processing. We should add that to:
https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#71-pre--and-post-processing

**Comment by tjablin** [comment]
Everyone is allowed to do architecture specific pre-processing. For example padding or transposing the input. What sort of bad behavior are you trying to disallow?

**Comment by christ1ne** [comment]
e.g. map all rare categorical values to a special ‘missing category’ value for DLRM

**Comment by tjablin** [comment]
I think that is already disallowed:

> Incorporating explicit statistical information about the performance or accuracy sets (eg. min, max, mean, distribution)
