### ISSUE TITLE
Update rules for inference v0.7

### ISSUE THREAD

**Issue by TheKanter** [mlperf/inference_policies#134]
We should update the inference rules to be consistent with what we agreed upon for v0.7

**Comment by christ1ne** [comment]
1) BM / models / datasets list not current - Peter
2) the scenarios are not current - Peter
3) open - retraining rules link and wording missing - David
4) model equivalence section update (section 8) -  Dilip to file PR
5) mobile will be an independent update later, as a delta from the main inference rules.

**Comment by christ1ne** [comment]
@petermattson friendly reminder before meeting tomorrow!

**Comment by TheKanter** [comment]
Also update FAQ to include DLRM embedding sorting Q&A.

**Comment by christ1ne** [comment]
@DilipSequeira anything else?

**Comment by DilipSequeira** [comment]
Created PRs for #128  and #129.

**Comment by DilipSequeira** [comment]
Also, did we ever resolve the density discussion: you should submit all benchmark/scenario combinations of which the SUT is capable?

**Comment by christ1ne** [comment]
> Created PRs for #128 and #129.

both closed 



> Also, did we ever resolve the density discussion: you should submit all benchmark/scenario combinations of which the SUT is capable?

This is also clarified in the rules
