### ISSUE TITLE
Is internal large cluster considered as available?

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#145]
Each chip is available but people cannot buy them to the cluster due to the cluster size.

**Comment by tjablin** [comment]
The rules say for Available say:

> Supply and lead times are appropriate for system scale, i.e. on-demand and in quantity for the smallest systems and a few months and with limited supply for the largest systems.

For a sufficiently large cluster a lead time of 12 - 18 months might be reasonable.

**Comment by TheKanter** [comment]
WG agrees this is OK.
