### ISSUE TITLE
Is private cloud counted as "available"

### ISSUE THREAD

**Issue by aaronzhongii** [mlperf/inference_policies#146]
[Here](https://www.alibabacloud.com/product/apsara-stack) is the introduction of Alibaba cloud apsara stack. Alibaba cloud provide apsara stack to enterprise/business customers for their special needs. 

Contrast to Alibaba public cloud, there is no webpage for you to select, click and buy. The enterprise customers needs to work with Alibaba engineering team to select the hardware configuration, the construction of the cloud and how to deploy. 

So my question is, is private cloud counted as "available"?

**Comment by tjablin** [comment]
The rules for Available say:

> Access to rent or purchase may be subject to conditions that are common to generally available products (such as financial qualifications, size of customer, support burden, export restrictions, etc.) but is not otherwise restricted (i.e. no “early access” approval requirements).

**Comment by aaronzhongii** [comment]
> The rules for Available say:
> 
> > Access to rent or purchase may be subject to conditions that are common to generally available products (such as financial qualifications, size of customer, support burden, export restrictions, etc.) but is not otherwise restricted (i.e. no “early access” approval requirements).

So as long as customer can rent the hardware through some efforts, just not restricted by "early access", it should be considered as available. Thanks for the answer.

**Comment by TheKanter** [comment]
1. Apsara is currently in production with many customers
2. Access is for 'private cloud' customers only
3. Private cloud customers is about commitment of $, and generally open to everyone

Accordingly WG determines this is fine.
