### ISSUE TITLE
does open division need to share source code or just the binary?

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#147]
This is for the case when people may not want to share the graph optimization technique. Question from Frank/Alibaba.

**Comment by tjablin** [comment]
The rules say:

> Source code used for the benchmark implementations must be open-sourced under a license that permits a commercial entity to freely use the implementation for benchmarking. The code must be available as long as the results are actively used.

There's a distinction between the benchmark implementation and the framework. The framework is stuff like compilers, drivers, and runtimes that are provided as binary artifacts to end-users.

**Comment by TheKanter** [comment]
Clarified in WG:

1. In open division, you can freely modify the model as long as you meet the scenario requirements.
2. In open division, you must share the modified/resulting model.

**Comment by frank-wei** [comment]
@TheKanter can we document this into the rules. 
One more thing to clarify, in Open division, the submitter can choose to submit any scenario or not?
