### ISSUE TITLE
Required scenarios for the Open division

### ISSUE THREAD

**Issue by psyhtest** [mlperf/inference_policies#151]
From the v0.7 round, most benchmarks in the Datacenter suite require the Server and Offline scenarios, and all benchmarks in the Edge suite require the SingleStream and Offline scenarios. Is the same also true for the Open division?

For example, is it valid to submit to the Open division only a SingleStream result for a non-ResNet50 Image Classification workload?

As another example, does a submitter needs to obtain and submit a SingleStream and Offline results, if they only really want to submit a MultiStream result?

**Comment by DilipSequeira** [comment]
My understanding (and I think the general understanding) is that on open, any combination of scenarios can be submitted. It's missing from the rules though.

@psyhtest I imagine if you had a PR to that effect, it might be something the working group could quickly close out.

**Comment by psyhtest** [comment]
Thanks @DilipSequeira. Here it comes: https://github.com/mlperf/inference_policies/pull/154

**Comment by guschmue** [comment]
We'd need to change this table in the rules doc:
https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#41-benchmarks
Each **Edge** benchmark requires the following scenarios: SingleStream, Offline

**Comment by christ1ne** [comment]
we updated the rules
