### ISSUE TITLE
Prior approval to place queries in device memory

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#152]
NVIDIA seeks prior approval to place query samples in device memory. In an optimized implementation we expect suitably advanced customers to leverage [GPUDirect](https://developer.nvidia.com/gpudirect) to avoid transfers through host DRAM. We will provide system architecture details and relevant performance information in our submission. 

Available software for GPUDirect:

- [GPUDirect Video](https://developer.nvidia.com/gpudirectforvideo), supported by many 3rd party video SDKs.
- GPUDirect storage 0.7 beta, available to qualified customers.

"Qualified customer" here means "customers at suitable scale who are doing bare-metal user-space performance optimization" (i.e. interested in using CUDA APIs to schedule data transfer.) My interpretation of the rules is that this meets the definition of Available for software, and is thus covered by the "Available Beta" clause.

**Comment by tjablin** [comment]
LGTM. I'm surprised you don't have a GPUDirect NIC example.

**Comment by christ1ne** [comment]
Is this for data center or edge or both? Thanks! @DilipSequeira

**Comment by DilipSequeira** [comment]
@christ1ne both data center and edge potentially.

**Comment by TheKanter** [comment]
Approved by working group.
