### ISSUE TITLE
Random seeds distribution timeline

### ISSUE THREAD

**Issue by psyhtest** [mlperf/inference_policies#153]
[Currently](https://github.com/mlperf/policies/blob/master/submission_rules.adoc#42-single-submission-round-schedule), the random seeds for are to be distributed only 1 week before the deadline. What if my SUT is available to me now, but is not going to be available then? A similar problem arises if runs are expected to take several days (as may well be the case for Edge submissions: https://github.com/mlperf/inference_policies/issues/150).

**Comment by christ1ne** [comment]
WG: we will move this to 2 weeks. @psyhtest please update with a PR and I will merge it later.

**Comment by christ1ne** [comment]
pick a irrational number and multiply it with a multiple of 2 -- currently assign to @TheKanter

**Comment by tjablin** [comment]
Suggestion procedure for David:

1. Go to https://www.random.org/bytes/
2. Set number of bytes to 8.
3. Set format to hex.
4. Press "Get Bytes"
5. Record seed.
6. Repeat 3x

**Comment by psyhtest** [comment]
> Repeat 3x

Ah, as we have 3 seeds, should we rephrase the rules (seed -> seeds)?

> The fixed seed will be announced two weeks before the benchmark submission deadline.
