### ISSUE TITLE
Approved loadgen commit SHAs for submission

### ISSUE THREAD

**Issue by mthmsn** [mlperf/inference_policies#163]
For inference v0.5, there were specific git commit SHAs that were approved for submission use. What are the blessed SHAs for v0.7? Is it any commit SHA after a specific date (e.g., any commit after the code freeze date in the schedule)?

I looked around a bit and can't find these SHAs listed anywhere yet.

**Comment by TheKanter** [comment]
DK to do with  Guenther assistance on 9/4.

**Comment by christ1ne** [comment]
mlperf.conf updated at mater.
