### ISSUE TITLE
Clarify which LoadGen log files are optional

### ISSUE THREAD

**Issue by psyhtest** [mlperf/inference_policies#165]
I believe including `mlperf_log_trace.json` was optional for v0.5. It was only included 156 times:
```
$ find submissions_inference_0_5 -name mlperf_log_trace.json  | wc -l
156
```

Also, `mlperf_log_accuracy.json` was optional for performance runs (as empty anyway).

Any other examples?

We should clarify this in the rules.

**Comment by christ1ne** [comment]
@guschmue  can submission rules be the source of truth in this?

**Comment by guschmue** [comment]
sure, we can make it optional. I think it was required in v0.5 but we did allow for errors from the checker.

**Comment by psyhtest** [comment]
`mlperf_log_accuracy.json` can be optional for the performance mode, but not for the accuracy mode. `mlperf_log_trace.json` can be optional for both modes.

**Comment by guschmue** [comment]
yes, that is what the PR is doing.

**Comment by nvpohanh** [comment]
This will be fixed by https://github.com/mlperf/policies/pull/53
