### ISSUE TITLE
Tail latency for Server/MS scenarios are outdated in the inference rules.

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#166]
The updated info for v0.7 is at:
https://docs.google.com/presentation/d/1urn23orVQq5Z5Jz8ZJf_o1dASlhIWDSLYi2fyuEY4hw/edit#slide=id.g8aa93609e1_0_0

Currently the rule says: 
99% for image models and 97% for otherwise
https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#3-scenarios

A rule update is needed.

**Comment by psyhtest** [comment]
It appears that the minimum number of queries should also be updated to 270,336.
