### ISSUE TITLE
The submission checklist must be updated (or made optional)

### ISSUE THREAD

**Issue by psyhtest** [mlperf/inference_policies#170]
[submission_checklist.md](https://github.com/mlperf/inference_policies/blob/master/submission_checklist.md) has not been updated for v0.7. Moreover, the [relevant subsection](https://github.com/mlperf/policies/blob/master/submission_rules.adoc#submission-checklist) of the submission rules is empty.

**Comment by mthmsn** [comment]
Thanks for posting this, I was just about to submit the same issue.

New submitters will be unaware of the `submission_checklist` relic. It definitely adds to the tedium of the submission process. The checklist itself is somewhat confusing and does not add any new information that isn't already available in the other submission files, other than the names of the engineers who "certify" the submission. I suggest it be made optional, removed entirely, or reduced to only include the top 2 lines:
```
Name of Certifying Engineer(s):

Email of Certifying Engineer(s):
```

**Comment by tjablin** [comment]
Some of the compliance questions are still useful, I think. 

> What untimed pre-processing does the submission use?
> Which of the following techniques does the submission use?

**Comment by tjablin** [comment]
I updated to 0.7. Many of the questions are no longer necessary with the new submission checker scripts. I think the remaining questions are still useful.
