### ISSUE TITLE
Definition of "random" for audit

### ISSUE THREAD

**Issue by TheKanter** [mlperf/inference_policies#178]
1. Audit group recommends that the random audit be determined before the 'strategic'/'interesting' audit.

A. How do we determine the scope of random audit. E.g., do we randomly select (1) a submitting organization and then random a submission by the submitter, (2) a submission, (3) a unique HW/SW combo, or (4) a member of the review committee.

B. Audit group suspects that some submissions may use HW/SW components where the owner of the HW/SW component is not submitting. E.g., Google is not submitting for inference v0.7, but someone rents a TPU to submit. Audit group also expects that some submitters (e.g., OEMs/cloud providers) may submit systems using a variety of 1st and 3rd party components (e.g., GPU, CPU, TPU).

2. Audit group recommmends the following randomization:

Random pool is each unique submitter.
Randomly select a submitter from the pool and then randomly select a submission by the submitter.

Randomization to be performed by David Kanter using a RNG.

**Comment by christ1ne** [comment]
added to rules
