### ISSUE TITLE
ReLU in model equivalence

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#19]
ReLU6 / ReLU8 is an allowed equivalence. We request this be extended to ReLU N for any N, including FLT_MAX.

**Comment by tjablin** [comment]
I think this is already allowed by the rules, and I think it is reasonable to make it explicit. I think change from one ReLU to another just adds a scaling factor, which ought to be allowed under mathematical equivalence. In particular:

> Mathematically equivalent transformations (e.g. Tanh versus Logistic, Relu6 versus Relu8) or approximations and including but not limited to transcendental functions (or equivalent transformations)

**Comment by DilipSequeira** [comment]
It modifies the scaling factor iff you're using quantization.

**Comment by tjablin** [comment]
Even for floating point,

`
ReLU(X, Activation) = 
max(min(Activation, 0), X) = 
max(min(Activation / X, 0), 1) * X =
max(min(Activation * Y / X, 0), Y) * X / Y =
ReLU(Y, Activation * Y / X) * X / Y
`

Right?

**Comment by DilipSequeira** [comment]
Thanks, I see what you meant by "just adds a scaling factor" now.

**Comment by christ1ne** [comment]
WG suggest rule change: ReluM versus ReluN

**Comment by tjablin** [comment]
Addressed in [PR27](https://github.com/mlperf/inference_policies/pull/27). PTAL.

**Comment by christ1ne** [comment]
rule updated
