### ISSUE TITLE
clarify mixing of precisions in quantization rules

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#2]
https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#81-weight-definition-and-quantization

we should add: mixing of any white listed precision is allowed. This is missing in the current doc.

**Comment by tjablin** [comment]
Is this already captured by 

- Hand picking different numerical precisions for different operations

In Section 8.2?

**Comment by christ1ne** [comment]
It is not obvious to me 'Hand picking different numerical precisions for different operations' is for quantization. I just want the rule to be very explicit in terms of quantization process.

**Comment by TheKanter** [comment]
I'm not sure what you are asking. The rules already state: "...to any combination of permissive whitelist numerical format that achieves the desired quality". That seems to cover a scenario where e.g., one tensor is FP11 and another is INT8.

Is your question about the quantization process itself and what data types can be used there? I would argue anything (in fact, you could use things outside the whitelist, but the result must be a combination of things on the whitelist).

What is the scenario that you are trying to ensure is covered?

**Comment by tjablin** [comment]
If we all agree that mixing quantized precisions is allowed (and I think we do), we should just update the rules to make it sufficiently explicit that everyone is satisfied.

**Comment by christ1ne** [comment]
thanks @TheKanter now I see the sentence. Sorry I did not read it closely.
