### ISSUE TITLE
Wrong quantization rules

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#24]
I don't think we have the right standard for exposing quantization - much though I would be interested to see how everyone else is doing it, what we should really care about is that it's a function of the input model and the calibration set, and generalizes across a wide range of models.

That's less strict than publishing it to the level of detail where it can be reproduced.

**Comment by christ1ne** [comment]
@DilipSequeira please provide an example to discuss more concretely.

**Comment by jveejay** [comment]
@tjablin would you please update the rules to include this sample description in the rules so that people will find it useful? 

https://docs.google.com/document/d/1L58URvzHslLn5C9P2WLptbJ-ut74wwO228DieIOEFh0/edit?ts=5d49eaad

**Comment by tjablin** [comment]
@DilipSequeira Can you upload your document as a canonical example of a quantization algorithm description so we can link it from the rules?

**Comment by christ1ne** [comment]
We should also keep in mind that if the submitter has the code opensourced, we don't need a doc when we have the actual code.

**Comment by DilipSequeira** [comment]
uploaded in calibration/doc

**Comment by christ1ne** [comment]
Need Rule update mandating quantization doc to be submitted X days before the submission deadline or full source code submitted on the submission date.

**Comment by christ1ne** [comment]
we will walk through the comments in the rules doc next week.

**Comment by christ1ne** [comment]
will be addressed in submission rules doc
