### ISSUE TITLE
Pruning?

### ISSUE THREAD

**Issue by tjablin** [mlperf/inference_policies#29]
I thought we agreed to disallow pruning, but the rules don't reflect this. Can we please update the rules to either allow or disallow pruning in the Closed division?

**Comment by samgd** [comment]
Is this a problem given closed prevents retraining? I'd be very surprised if you can gain a non-trivial level of sparsity with post-training quantisation only?

**Comment by samgd** [comment]
However I should probably add that for the rules I think explicit is generally better than implicit so I'm generally for this inclusion

**Comment by DilipSequeira** [comment]
Is it not covered by the more general prohibition on discarding non-zero weight elements?

**Comment by tjablin** [comment]
I think it ought to be covered by that rule, but I'd prefer the rules were more explicit.

Discarding non-zero weight elements -> Discarding non-zero weight elements and pruning.

**Comment by DilipSequeira** [comment]
I'm all for clarification. I would rather say "including pruning", if it's just to provide emphasis. If it's a semantic change, we should be clear what it is.
