### ISSUE TITLE
Padding/Transposing/Reshaping in Accuracy Mode

### ISSUE THREAD

**Issue by tjablin** [mlperf/inference_policies#3]
Some inference systems may produce outputs that are arbitrarily padded, transposed, or reshaped relative to the reference implementation. In real systems, downstream code can frequently be adapted to read inputs in unusual layouts. Should adapters be allowed for connecting the reference accuracy checking code?

**Comment by petermattson** [comment]
Isn't this insignificant from a timing perspective?

**Comment by tjablin** [comment]
Probably. I just want an official resolution.

**Comment by DilipSequeira** [comment]
This seems to me to be essentially the same question as input transpose - i.e. we should have a (non-empty) set of possible output adapters: the obvious ones (transposition) and by request.

**Comment by jveejay** [comment]
At the end of the day, does all this matter for timing? I thought that output accuracy is not being timed similar to whatever transformations done during the early stages?

Typed on a small screen, excuse brevity and typos.
vj.

________________________________

**Comment by tjablin** [comment]
If we allow some sort of output adapter, we have to make rules about it. The easiest solution is to require post-processing to be timed. 

Per VJ's comment, accuracy mode is untimed. The question is whether an adapter is allowed in accuracy mode that was not present in performance mode.

**Comment by DilipSequeira** [comment]
I would start with whitelisting:

1. an arbitrary transpose
2. precision conversion

I expect the only case is what format the bounding boxes are delivered by the object detection network, but I'm not sure why we're even asking people to pay for that.

**Comment by christ1ne** [comment]
conclusion: same code must be run for accuracy and performance for v0.5 only. Need to review for segmentation. Need rule update in FAQ @jveejay

**Comment by christ1ne** [comment]
rule updated per WG agreement.
