### ISSUE TITLE
alternative calibration set proposal

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#35]
An alternative proposal:
       ImageNet: first 500 images and class labels.
       COCO: first 500 images and annotations.

The current calibration sets are also 500 images each but randomly chosen (?).

**Comment by tjablin** [comment]
What's the rationale for this proposal? Random selection without replacement is very likely representative. The first 500 images may be unrepresentative.

**Comment by christ1ne** [comment]
updated the set according to the request of 1 class each. 
[calibration_2.txt](https://github.com/mlperf/inference_policies/files/3498015/calibration_2.txt)

**Comment by jveejay** [comment]
Does this calibration_2.txt address the issue you are facing @christ1ne ?

**Comment by christ1ne** [comment]
yes. @jveejay

**Comment by christ1ne** [comment]
image classification additional calibration dataset accepted by WG. README to be updated.
