### ISSUE TITLE
Error margin on accuracy or inaccuracy? 

### ISSUE THREAD

**Issue by cy89** [mlperf/inference_policies#4]
I commented on an email discussion:

For calibration, what's the current fp_trained_accuracy for the planned set of inference benchmarks? 

It seems to me that formulation in terms of the %correct might not be the right way to frame the error margin. The difference between 50% correct and 49% correct is probably negligible, but the difference between 99% and 98% correct is 2x more errors. None of which might matter if all of the current inference benchmarks are at 70% correct in float, but if anything is above 90%, then we're allowing very wide error margins for the high-accuracy benchmarks that might not represent what people want to deploy. 

So, recommendations: 
1. Can we please state what current accuracies people think apply for floating-point inference today? If we're currently 75% accurate / 25% inaccurate, the distinction I'm raising is probably moot. But if we're closer to 99% accurate, we should be careful not to widen our accuracy margins by ridiculous factors because of how the math work.
2. Please discuss: do people have opinions about %increase in errors versus %decrease in correct_percent?

**Comment by petermattson** [comment]
Good point, believe it is presently moot.

**Comment by christ1ne** [comment]
WG: we agree to set good accuracy targets at per model level for this round. Agree with the point.
