### ISSUE TITLE
clarify the SW availability

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#45]
Currently the rule says:
2.3. System and framework must be available
If you are measuring the performance of a publicly available and widely-used system or framework, you must use publicly available and widely-used versions of the system or framework.

If you are measuring the performance of an experimental framework or system, you must make the system and framework you use available upon demand for replication.

--
In training, we allowed PRs to frameworks to be allowed. How shall we reflect this in the rules?
How about closed source code and binaries? Do we require them to be on an official site? What defines to be an official site?

**Comment by tjablin** [comment]
> In training, we allowed PRs to frameworks to be allowed.

Is that correct? I thought there was some carefully negotiated verbiage about tagged releases?

**Comment by christ1ne** [comment]
Condition for available systems:
1. Identified version. SW available upon purchase or rental or for download. we need these versions information to be public and officially supported for all customers.  
2. if use main framework (e.g. TF, PyTorch), any branch is ok, optionally to add a public PR from submitter 

to be updated in the inference submission rules doc.

**Comment by christ1ne** [comment]
updated in the submission doc, to be uploaded by @petermattson
