### ISSUE TITLE
goal of server scenario

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#5]
Is the server scenario for 
1) all devices including phones?
2) actual HW which are targeting datacenter servers?

If 1) I suggest we set a few latency targets and don't force everyone to submit to the same latency targets. We also need to clarify in the rules that server scenario is a testing mode, not targeting a real server use case. 

If 2) I suggest we set latency targets which represents actual data center use cases.

Thanks.

**Comment by tjablin** [comment]
The server scenario is modelling datacenter workloads. The latency targets are relatively permissive since this is MLPerf Inference 0.5. Ideally, the latencies will drop in the next round. If everyone agrees to drop the latency targets, I think we should do so.

**Comment by christ1ne** [comment]
WG rec we should set realistic latency targets for real datacenter use cases. so it is 2. Result presentation should not have phones next to server HWs, for example.
