### ISSUE TITLE
pre-processing per row data padding due to hardware alignment requirement

### ISSUE THREAD

**Issue by aaronzhongii** [mlperf/inference_policies#51]
Just want to know whether per row data padding to match with hardware's alignment requirement is untimed or not.

**Comment by tjablin** [comment]
The text in Section 7.1 says that untimed pre-processing:

> May pad to arbitrary size (don’t be creative)

You should feel free to pad to the hardware's required alignment during untimed pre-processing.

**Comment by aaronzhongii** [comment]
> The text in Section 7.1 says that untimed pre-processing:
> 
> > May pad to arbitrary size (don’t be creative)
> 
> You should feel free to pad to the hardware's required alignment during untimed pre-processing.

I thought that "pad" refers to padding on the image dimensions. So it's not?

**Comment by tjablin** [comment]
My reading is that you may pad the batch, image, channel, or other dimensions.

**Comment by christ1ne** [comment]
WG approved and close.
