### ISSUE TITLE
image preloading

### ISSUE THREAD

**Issue by aaronzhongii** [mlperf/inference_policies#55]
Can we give driver a hint to preload the image data to somewhere closer to chip during LoadSamplesToRam?

**Comment by tjablin** [comment]
The relevant rules are:

> The trace generated by LoadGen must be stored in the non-HBM DRAM that most faithfully simulates queries arriving from the most logical source, which is usually the network or an I/O device such as a camera. It may be pinned. Submitters need prior approval for anything that is not DRAM.

and 

> Caching of any queries, any query parameters, or any intermediate results is prohibited.

Depending on the exact operation of the hint, I think this violates either the first rule or the second.

**Comment by aaronzhongii** [comment]
Tom,

Thanks for the clarification.

**Comment by aaronzhongii** [comment]
> The relevant rules are:
> 
> > The trace generated by LoadGen must be stored in the non-HBM DRAM that most faithfully simulates queries arriving from the most logical source, which is usually the network or an I/O device such as a camera. It may be pinned. Submitters need prior approval for anything that is not DRAM.
> 
> and
> 
> > Caching of any queries, any query parameters, or any intermediate results is prohibited.
> 
> Depending on the exact operation of the hint, I think this violates either the first rule or the second.

Tom,

Thanks for the clarification. What if the memory is still DRAM, but at a special region readable by hardware?

**Comment by tjablin** [comment]
My interpretation is that accessing inputs in host memory from the device via the IOMMU is allowed, but accessing inputs in device memory from the host via the IOMMU is not allowed.

The rule should help you identify a unique physical memory that is the most logical place for inputs from network or camera to arrive. Every query should start in that memory.

**Comment by aaronzhongii** [comment]
> My interpretation is that accessing inputs in host memory from the device via the IOMMU is allowed, but accessing inputs in device memory from the host via the IOMMU is not allowed.
> 
> The rule should help you identify a unique physical memory that is the most logical place for inputs from network or camera to arrive. Every query should start in that memory.

cool, thanks

**Comment by christ1ne** [comment]
add this to FAQ in the rules. @tjablin list examples

**Comment by tjablin** [comment]
Addressed in PR #68. PTAL.
