### ISSUE TITLE
Is it available to use a web API based compilation?

### ISSUE THREAD

**Issue by kstreee-furiosa** [mlperf/inference_policies#58]
Hi all,

In our cases, we commonly use and provide a web API based compiler for internal development & customers for security reasons.
Likewise, we hope to compile models using the web API based compiler during MLPerf inference submissions too. (obviously, auditors can use the compiler via web API in our inference submission system).
Is it available to consist our compilation process like this during inference submissions?

**Comment by tjablin** [comment]
WG approves.

**Comment by tjablin** [comment]
Please indicate the version of the web API based compiler so the results are reproducible even if the compiler has been updated since.
