### ISSUE TITLE
Long Offline Runs

### ISSUE THREAD

**Issue by tjablin** [mlperf/inference_policies#6]
For the offline scenario, can a run that is much longer than the minimum number of queries and the time duration be submitted?

**Comment by petermattson** [comment]
Fundamentally, this is about: what is the expected runtime of an offline inference job?

**Comment by tjablin** [comment]
Some systems need longer runs to reach peak throughput even with a warmup. Suppose you have an inference server on the Moon. Round trip time to the moon is about 3 seconds. A sixty second offline inference run on a Moon server only have 57 seconds of Moon computation. In general, longer runs should be more indicative of real performance than shorter runs.

**Comment by christ1ne** [comment]
WG agrees there is no official cap to the offline mode. Assign to @tjablin

**Comment by tjablin** [comment]
Addressed in [PR28](https://github.com/mlperf/inference_policies/pull/28). PTAL.
