### ISSUE TITLE
clarify accuracy run is needed for every performance run.

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#60]
Right now a submission to any model should have: 
1. accuracy run with single stream (mandatory)
2. performance run with single stream (optional)
3. performance run with multi-stream stream (optional)
4. performance run with server stream (optional)
5. performance run with offline stream (optional)
At least one of 2-5 above should be submitted. 

In the rules, it states: 
Note: For v0.5, the same code must be run for both the accuracy and performance LoadGen modes.

I suggest we change it to:
Note: For v0.5, the same code must be run for both the accuracy and performance LoadGen mode with single stream. 

@briandersn how would 'SubmissionRun' work in loadgen with the scheme above?

**Comment by tjablin** [comment]
Addressed in PR #67. PTAL.

**Comment by christ1ne** [comment]
closed as the rule updated
