### ISSUE TITLE
Query Library Size determination

### ISSUE THREAD

**Issue by jveejay** [mlperf/inference_policies#61]
We need to determine the QSL size. Currently, 1000 and 500 are being debated.
 
Please see link [here](https://docs.google.com/presentation/d/1o9MK0yZVffTPoBH9zI91NYBfnGt0_qnFn2awd6tnDqU/edit#slide=id.g5e24ddb9cc_0_35).

**Comment by tjablin** [comment]
Created PR #66 to resolve the issue. PTAL.

**Comment by christ1ne** [comment]
WG will decide next week 500 vs 3072 for Resnet50.

**Comment by psyhtest** [comment]
FWIW, the state-of-the-art [Google Coral dev board](https://coral.withgoogle.com/docs/dev-board/datasheet/) has 1 GB RAM.

**Comment by christ1ne** [comment]
Finally we determined 1024 for Resnet . @tjablin to update the rules

**Comment by tjablin** [comment]
ResNet: 1024
ResNet MobileNet: 1024
SSD-MobileNet: 256
SSD-1200: 64

**Comment by christ1ne** [comment]
rule updated.
