### ISSUE TITLE
Questions about team member?

### ISSUE THREAD

**Issue by wangweiw** [mlperf/inference_policies#62]
Hi, Results WG, we have a  question that we are doing NMT Inference benchmark with some engineers from another company, can we metion their names (like XXX from XXX)in the results publicaion?

**Comment by psyhtest** [comment]
I've got a similar question.

**Comment by christ1ne** [comment]
will it be OK to list the submitter as an string like 'company_A, company_B'

**Comment by tjablin** [comment]
@christ1ne that sounds totally reasonable. Do you have a rules citation to confirm it? Do we need codified rules for this? Maybe it's okay to leave this uncodified? What do you think?

**Comment by christ1ne** [comment]
In addition, if company_A and company_B did a submission together, it is up to company_A and company_B to decide who's name or both names to be listed in the submitter column. Meanwhile, at least one of the displayed names needs to be a pre-registered submitter.

**Comment by christ1ne** [comment]
WG agree without a rule update.
