### ISSUE TITLE
Loadgen: Need clarification on usage of total_sample_count which is part of QSL

### ISSUE THREAD

**Issue by rachithayp** [mlperf/inference_policies#63]
For "Performance mode", I am trying to understand if there are specific expectations on the value the parameter "total_sample_count" in QSL should be set to. Can this be random value?. Please help provide clarification. 
For "Accuracy mode" I am assuming this will be equal to the entire Validation set.

**Comment by briandersn** [comment]
"total_sample_count" in the QSL depends on the dataset used. It will have the same value for performance and accuracy modes and is not random.

The "performance_sample_count" is the number of samples to select from the total_sample_count, corresponding to a subset of the QSL that can fit in device RAM.

**Comment by jveejay** [comment]
@rachithayp can we close this out or do you need more clarification?

**Comment by rachithayp** [comment]
Closing, thank you.
