### ISSUE TITLE
Increase GNMT query library size to avoid implicit caching.

### ISSUE THREAD

**Issue by briandersn** [mlperf/inference_policies#64]
There are a small number of queries in the GNMT sample set.

In order to avoid all samples being implicitly cached, can we increase the GNMT source queries by having N copies of the samples such that they take up 512MB?

In order to avoid changing the loadgen API for v0.5, we could increase the size of the library itself and allow the performance size to be larger than the accuracy size in the QSL.

cc: @tjablin, @nvmbreughe

**Comment by tjablin** [comment]
The 3003 sentences in newstest2014 from WMT16 English-German.

**Comment by christ1ne** [comment]
the proposal is contacting the dataset itself for multiple times to have size ~512MB. @nvmbreughe  any inputs?

**Comment by nvmbreughe** [comment]
I don't think there would be any problem by replicating the 3003 sentences several times. Copy-pasting the text file will do the trick. Should we change the number of queries to match it, i.e., [L509](https://github.com/mlperf/inference/blob/master/v0.5/translation/gnmt/tensorflow/loadgen_gnmt.py#L509) ?

**Comment by christ1ne** [comment]
I think we may need to double check on BLEU score.

**Comment by christ1ne** [comment]
@nvmbreughe please concat the text and issue a PR.

**Comment by briandersn** [comment]
There's also a potential loadgen component to this, where we may want to allow the QSL performance set size to be greater than the "total" size. Or add an accuracy set size, if we are willing to change the API.

**Comment by nvmbreughe** [comment]
Sorry for the delay. I will be looking into this today.

**Comment by tjablin** [comment]
For accuracy mode, I think running on the 3003 original sentences will be sufficient.

**Comment by nvmbreughe** [comment]
@christ1ne , I am working on a PR and have the new (513MB) input file ready: https://we.tl/t-djJZpR8YQO. Could you please help me update the tarball in the download link again?

**Comment by christ1ne** [comment]
@nvmbreughe please see the updated link at https://zenodo.org/record/3437893/files/gnmt_inference_data.zip
I kept the original files and uploaded the new larger set nmt/data/newstest2014.tok.bpe.32000.en.large

I accidentally included a .zip file but I think we can just ignore it for now.

Please update in read me that performance mode uses .en.large while the accuracy mode uses the original .en per Tom's command.

Please review the files and let me know if there is any issue. 

Thanks!

**Comment by tjablin** [comment]
After [PR427](https://github.com/mlperf/inference/pull/427) lands, we still need to update the minimum QSL size for NMT in the rules.

**Comment by riking** [comment]
Reopen for rules update

**Comment by tjablin** [comment]
We still need the rules update. Can we please try to have a PR ready before the rules meeting on Tuesday?

**Comment by DilipSequeira** [comment]
PR #91.

**Comment by christ1ne** [comment]
done
