### ISSUE TITLE
clarification on preprocessing text for GNMT

### ISSUE THREAD

**Issue by mlazos** [mlperf/inference_policies#72]
Is mapping words in a sentence sample to embedding indices an acceptable form of preprocessing when loading text samples to RAM? There are many whitelisted int variants and conversions to white listed data types are permitted :)

**Comment by tjablin** [comment]
I think the rules allow this because Section 7.1 says the whitelisting:

> May convert data among all the whitelisted numerical formats

Arguably, the mapping is a conversion from one quantized format to another. Maybe other people disagree?

I think mapping to embedding **indices** is allowed and mapping to **embeddings** is disallowed.

**Comment by mlazos** [comment]
I agree that's where I think the line is drawn, but what stops us from extending the argument to saying embeddings are a whitelisted format as well as the indices?

**Comment by tjablin** [comment]
I think the principle is that mapping from a token to an index just changes from one representation of a number to another. It's not different than changing from two's complement to one's complement. Mapping from token to embedding changes a value into a row and increases the rank of the tensor. A "row" is not one of the enumerated acceptable quantization formats.

**Comment by tjablin** [comment]
WG approves interpretation. Mapping indices is okay. Mapping embeddings is not valid.
