### ISSUE TITLE
multi stream latency constrain wrong ?

### ISSUE THREAD

**Issue by guschmue** [mlperf/inference_policies#77]
https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#41-benchmarks

mobilenet = 66ms
ssd-resnet34 = 50 ms

seems wrong. Need to swap this?

**Comment by tjablin** [comment]
Looking at the "MLPerf Cloud/Edge Inference Matrix" spreadsheet, the rules document seems to have transposed the numbers. Sorry. It's probably my fault. @guschmue, would you like to write a PR to swap the latencies or should I?

**Comment by guschmue** [comment]
sure can do.

**Comment by christ1ne** [comment]
done!
