### ISSUE TITLE
clarification for format conversion in pre-processing

### ISSUE THREAD

**Issue by aaronzhongii** [mlperf/inference_policies#78]
As the rules section 7.1 indicate
May convert data among all the whitelisted numerical formats

and as int8 is in white list format, float to int8 conversion is allowed in pre-processing.

We used calibration list 1 to profile the input tensor value range post pre-processing, the min max range is (-123.68, 151.06), thus to fit the input tensor into int8, a scale of 0.84 shall be multiplied, otherwise, out of range value will be clamped and precision will be affected.

Just want to clarify the scaling of 0.84 on opencv pre-processed value can be done in pre-processing process, which is not timed in performance mode.

**Comment by tjablin** [comment]
I believe that converting from F32 to Q8 includes any linear transform that is necessary to fit into the Q8 range. I think multiplying by 0.84 is allowed to be untimed.

**Comment by aaronzhongii** [comment]
thanks tom

**Comment by tjablin** [comment]
WG approves Multiplying by a constant as part of pre-processing is fine.
