### ISSUE TITLE
ResNet Classes and Probabilities

### ISSUE THREAD

**Issue by tjablin** [mlperf/inference_policies#8]
ResNet returns a tuple of tensors representing classes and probabilities. Are both necessary?

**Comment by christ1ne** [comment]
WG agreed you can dead code eliminate the probability (softmax), only argmax is needed. 
@tjablin  please update in FAQ

**Comment by tjablin** [comment]
Addressed in [PR32](https://github.com/mlperf/inference_policies/pull/23). PTAL.
