### ISSUE TITLE
terms of use typo?

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#81]
In the current terms of use:
https://github.com/mlperf/policies/blob/master/TERMS%20OF%20USE.md

You may cite either official results obtained from the MLPerf results page or unofficial results measured independently. If you cite an unofficial result you must clearly specify that the result is “Unverified” in text and clearly state “Result not verified by MLPerf” in a footnote. The result must comply with the letter and spirit of the relevant MLPerf rules. For example:

SmartAI Corp announced an estimated score of 0.3 on the MLPerf v0.5 Training Closed Division - Image Classification benchmark using a cluster of 20 SmartChips running MLFramework v4.1 [1].

[1] Result not verified by MLPerf. MLPerf name and logo are trademarks. See www.mlperf.org for more information.

--> actually 'Unverified' in not in example text. It only has 'estimated'

**Comment by christ1ne** [comment]
@petermattson  please fix it.

**Comment by petermattson** [comment]
Fixed in doc.
