### ISSUE TITLE
number of runs required, currently it is 5

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#82]

**Comment by tjablin** [comment]
> Single-stream: LoadGen measures average latency using a **single** test run. For the test run, LoadGen sends an initial query then continually sends the next query as soon as the previous query is processed.
> 
> Multi-stream: LoadGen determines the maximum supported number of streams using multiple test runs. Each test run evaluates a specific integer number of streams. For a specific number of streams, queries are generated with a number of samples per query equal to the number of streams tested. All samples in a query will be allocated contiguously in memory. LoadGen will use a binary search to find a candidate value. It will then verify stability by testing the value **5 times**. If one run fails, it will reduce the number of streams by one and then try again.
> 
> Server: LoadGen determines the system throughput using multiple test runs. Each test run evaluates a specific throughput value in queries-per-second (QPS). For a specific throughput value, queries are generated at that QPS using a Poisson distribution. LoadGen will use a binary search to find a candidate value. It will then verify stability by testing the value **5 times**. If one run fails, it will reduce the value by a small delta then try again.
> 
> Offline: LoadGen measures throughput using a **single test run**. For the test run, LoadGen sends all queries at once.

**Comment by tjablin** [comment]
> A 99% confidence bound was somewhat arbitrarily selected. For systems with noisy latencies, it is possible to obtain better MLPerf results by cherry picking the best runs. Approximately 1 in 100 runs will be marginally better. Please don’t do this. It is very naughty and will make the MLPerf community feel sad.

**Comment by tjablin** [comment]
So the number of times is only relevant for Server and Multi-Stream.

**Comment by christ1ne** [comment]
@briandersn @tjablin is the 5 times encapsulated within the loadgen? Will the user need to submit 1 set of logs or 5 set of logs for multi-stream and server? Just want to be absolutely clear.

**Comment by tjablin** [comment]
The LoadGen doesn't know. You have to run it five times and submit five logs or maybe the concatenation of five logs.

**Comment by christ1ne** [comment]
OK. we should have a small table in the rules like the following:

Number of runs per scenario entry (each run requires a complete set of logs)
Single Stream: 1
Multi-Stream: 5
Server: 5
Offline: 1

We may need to update the directory structure to add a run folder in the results. @petermattson @tjablin @guschmue

**Comment by tjablin** [comment]
There's a question for this in the Self-Certification form I sent you yesterday. What do you think about it?

**Comment by guschmue** [comment]
I read this language that this happens in loadgen. @briandersn, true ?

**Comment by tjablin** [comment]
In principle, it could happen in the LoadGen, but was it ever actually implemented? Do we want to implement at this late date?

**Comment by guschmue** [comment]
The text is: 
```LoadGen determines``` the maximum supported number of streams using multiple test runs.

While that is what we really want, I think somehow people did not trigger on this (ok, I'm one of them) and specify it manually.
Can take a look what it actually does later today.

**Comment by tjablin** [comment]
My interpretation is that this is a convenience feature and you can determine the maximum number of streams (or the maximum QPS) once and then hardcode it for future runs. You don't have to submit a log showing how you found the maximum. The log just validates that the systems passes at the maximum.

**Comment by guschmue** [comment]
There is definitely some support for the scan in loadgen, at least for server ... add a ```--find-peak-performance``` to the reference app to enable the FindPeakPerformance mode. As far I can tell that is working. Can we submit the results of that run or do we need to copy the qps and to a normal PerformanceMode run ?

**Comment by tjablin** [comment]
My unofficially and totally non-binding interpretation is that you can submit the results of --find-peak-performance plus four more runs with the settings you found.

**Comment by guschmue** [comment]
Just tested this a little for Server; works ok. It doesn't know early out and runs the full query  count on each step of the binary search which takes forever. But if you set the duration to 2 minutes or so its pretty handy.

So the question: if I pick a good initial qps and let it run to find the max qps ... that would be a valid submission without a separate PerformanceMode  run ?

The results are not totally stable: if I do 3 different runs queries completed/sec are in my case 200, 193, 180 ... 10%, that is quite a bit.

The summary looks like below (it is INVALID because I used only a 1000 queries)
```
Scenario : Server
Mode     : Find Peak Performance
Scheduled samples per second : 200.78
Result is : INVALID
  Performance constraints satisfied : Yes
  Min duration satisfied : NO
  Min queries satisfied : Yes
Recommendations:
 * Increase the target QPS so the loadgen pre-generates more queries.

Completed samples per second    : 200.65

Min latency (ns)                : 2201928
Max latency (ns)                : 12319844
Mean latency (ns)               : 4055386
50.00 percentile latency (ns)   : 3747207
90.00 percentile latency (ns)   : 6198663
95.00 percentile latency (ns)   : 7435882
97.00 percentile latency (ns)   : 8296263
99.00 percentile latency (ns)   : 9480683
99.90 percentile latency (ns)   : 12319844
....
```

**Comment by DilipSequeira** [comment]
I would suggest that for a run to be valid, it has to run at the stated QPS & QoS for the full query count with the supplied seed - but that whether that run was from find-peak-performance or not is immaterial.

**Comment by guschmue** [comment]
+1. 
Do we need to run it 5 times ? Server mode does 270336 queries and I assume that would be enough to make sure results are stable.
If we want submitters to run it 5x we'd need to remind them and we also need to say how we pick the number from those 5 results.

**Comment by tjablin** [comment]
In order to support a claim of 200 QPS in the Server scenario, you need five runs with QPS at least 200. If you have five runs with {201, 210, 205, 207, 202} QPS, that's sufficient to claim 200 QPS. I agree with Dilip's interpretation that "whether that run was from find-peak-performance or not is immaterial." The statical power of the techniques we are using to validate QPS (or number of streams) is such that one in a hundred runs are pretty substantially better. The requirement to do five runs is to try and counteract the temptation to cherry pick golden runs. In a perfect world, there would be a requirement to do the five runs back-to-back, but it's not the sort of thing we can realistically make a rule about.

Anyone whose logs show five runs at very different times on systems with different hostnames is kind of suspicious.

**Comment by willc2010** [comment]
maybe we should specify the time stamp on the loadgen log should be within X min to limit the numbers of total runs that the results can be cherry-picked from? Likely this will open a huge debate on what this X should be.

**Comment by tjablin** [comment]
> Likely this will open a huge debate on what this X should be.

This issue seems too hard to tackle through rule making. If someone has an idea about how to specify this, we should seriously consider it for MLPerf 0.6.

**Comment by christ1ne** [comment]
In the rules, we specify the multi-stream runs to be 270k. With resnet 50 where a query will arrive in every 50ms, each will take 262742*0.05/3600 = 3.6 hours. If we require 5 runs, it will take 18 hours.  I will recommend the total run time to be < 8 hours so that it can be done by 1 engineer and 1 system in 1 working day. What will we lost if we reduce 270k to 27k. @tjablin

**Comment by tjablin** [comment]
Cutting the required number of queries from 33 * 2^13 to 3 * 2^13 reduces the statistical power such that we would only really be able to enforce 90th percentile tail latency bounds. 90th percentile tail latency has weird consequences for NMT especially and raises the issue of soft-dropping again.

**Comment by tjablin** [comment]
If we have to compromise here, I would rather keep the number of queries constant and reduce the number of runs for the multi-stream scenario.

**Comment by christ1ne** [comment]
that's fine with me but I guess we need the WG approval

**Comment by tjablin** [comment]
If you open a PR, we can discuss on Tuesday.

**Comment by christ1ne** [comment]
ok

**Comment by tjablin** [comment]
WG recommends one run required only for Multi-Stream.

**Comment by christ1ne** [comment]
done
