### ISSUE TITLE
Source Code License

### ISSUE THREAD

**Issue by aaronzhongii** [mlperf/inference_policies#83]
is it mandatory to use apache 2.0 for source code in submission the same as loadgen do? can we use other licenses, such as GPL or proprietary license?

**Comment by christ1ne** [comment]
all code within MLPerf submission repo needs to be Apache 2.0. However, you can always pull code from external repo in your submission script, which may have different licenses.

**Comment by aaronzhongii** [comment]
ok, thanks

**Comment by christ1ne** [comment]
please reopen if further issues.
