### ISSUE TITLE
Use the reference code to determine which LoadGen API is mandatory?

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#84]
Right now I don't see the following 2 LoadGen API in the reference code: 
- ReportLatencyResults()  
- UnloadSamplesFromRam()

Can I assume they are not needed for the submission?
@briandersn @tjablin @guschmue

**Comment by tjablin** [comment]
In our implementation LoadSamplesFromRam unloads all prior LoadSamplesFromRam and LoadSamplesFromRam is a no-op. I think this is allowed. I think implementing ReportLatencyResults is allowed.

**Comment by christ1ne** [comment]
@tjablin I'm sure people can use all the APIs which loadgen provides. The question is that if we can use the reference implementation to determine which loadgen APIs are mandatory in the submissions.

**Comment by tjablin** [comment]
For the two APIs you mention, I think it is acceptable to implement them as no-ops.

**Comment by guschmue** [comment]
we register and implement UnloadSamplesFromRam but wipe the current samples in LoadSamplesFromRam as well so we don't care if it gets called or not.
If one does something wrong with this the accuracy numbers will be wrong.

**Comment by tjablin** [comment]
WG recommends that submitter can implement or not implement ReportLatencyResults and UnloadSamplesFromRam at their discretion.
