### ISSUE TITLE
code freeze date proposal for v0.5 

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#85]
I'd like to propose next Wed Sept 25 as the code freeze date for all SW except for compliance checking. In theory I think we can fix the directory structure and naming manually if needed.

What do you think? @jveejay @TheKanter @petermattson @guschmue @briandersn @tjablin @DilipSequeira

**Comment by jveejay** [comment]
Can we make it the end of the week @christ1ne as that will give us exactly two weeks, and it will also allow us to tell folks about the freeze on Tuesday and give time to lock things down if anything is afloat. I think there are one or two items that are afloat with SSD ResNet. Any others? 

In general, fully agree with you that we should freeze the code.

**Comment by christ1ne** [comment]
@ can we allow submitter to use any loadgen with commit hash starting this Wed? If we cannot separate user.conf and mlperf.conf, can we just leave the mlperf.conf as it is?

**Comment by tjablin** [comment]
WG recommends Friday Freeze.

**Comment by christ1ne** [comment]
done
