### ISSUE TITLE
Per scenario rules vs. per benchmark rules

### ISSUE THREAD

**Issue by psyhtest** [mlperf/inference_policies#90]
[Section 3](https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#3-scenarios) specifies the **Duration** and **Samples/query** metrics per scenario. [Section 4.1](https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#41-benchmarks) specifies the **QSL Size**, defined as "the size of the test set for each benchmark" for performance runs, per benchmark.

I have a couple of questions.

1) Suppose I would like to submit SSD-MobileNet in the SingleStream scenario on an SUT that takes 1 s per sample. Do I need 1024 samples (Section 3) or 256 samples (Section 4.1) for a valid performance run? (In either case, the test would take more than 60 s.)

2) Similarly, suppose I would like to submit MobileNet in the Offline scenario on an SUT that takes 100 ms per sample. Do I actually need 24,576 samples (Section 3) or 1024 samples (Section 4.1) would be sufficient for a valid performance run? (In either case, the test would take more than 60 s.)

3) Suppose I would like to submit MobileNet in the Offline scenario on an SUT that takes 1 ms per sample. Do I need to iterate ~2.4 times over 24,576 samples (Section 3) or 59 times over 1024 samples (Section 4.1) for a valid performance run?

4) Is it only allowed to process one sample (e.g. image) per query for the SingleStream scenario (Section 3)? Even for an accuracy run (where we need to process e.g. 50,000 images for ImageNet)?

**Comment by psyhtest** [comment]
By the way, `24576` has been [removed](https://github.com/mlperf/inference/commit/b94769ff0467628f0537669e12552cd22e22f3fc#diff-8ea4d56d28fe617b3ebc3dd431b194ed) from the reference code:
```
-    parser.add_argument("--queries-single", type=int, default=1024,
-                        help="mlperf number of queries for SingleStream")
-    parser.add_argument("--queries-offline", type=int, default=24576,
-                        help="mlperf number of queries for Offline")
-    parser.add_argument("--queries-multi", type=int, default=24576,
-                        help="mlperf number of queries for MultiStream,Server")
```
but not reintroduced into [`mlperf.conf`](https://github.com/mlperf/inference/blob/master/v0.5/mlperf.conf):
```
*.SingleStream.target_latency = 10
*.SingleStream.target_latency_percentile = 90
*.SingleStream.min_duration = 60000
*.SingleStream.min_query_count = 1024
...
*.Offline.target_qps = 1.0
*.Offline.target_latency_percentile = 90
*.Offline.min_duration = 60000
*.Offline.min_query_count = 1
```
I must have missed this discussion when I was away a couple of weeks ago?

**Comment by tjablin** [comment]
> Suppose I would like to submit SSD-MobileNet in the SingleStream scenario on an SUT that takes 1 s per sample. Do I need 1024 samples (Section 3) or 256 samples (Section 4.1) for a valid performance run? (In either case, the test would take more than 60 s.)

Section 3 says that a valid performance run for Single Stream must include at least 1024 queries and run for at least 60 seconds. Depending the speed of the SUT, it may be necessary to run for more than 60 seconds or more than 1024 queries. Section 4.1 indicates the minimum QSL size. For SSD-MobileNet, the minimum QSL size is 256. This means that the LoadGen should load at least 256 samples into DRAM before starting the clock and will then select samples uniformly randomly with replacement from the library of 256 samples. Given that the minimum number of queries is greater than the minimum QSL size and the number of samples per query is one is SingleStream mode, some samples will be sent to the SUT more than once.

In the example above, it is necessary to run for 1024 queries over 1024 seconds to meet both the query minimum and the duration minimum.

> Similarly, suppose I would like to submit MobileNet in the Offline scenario on an SUT that takes 100 ms per sample. Do I actually need 24,576 samples (Section 3) or 1024 samples (Section 4.1) would be sufficient for a valid performance run? (In either case, the test would take more than 60 s.)

In the example above, in order to meet both the sample minimum and the duration minimum, it is necessary to run one query with 24,576 samples or 245.76 seconds. The minimum QSL size is 1024 samples, so samples will be repeated.

> Suppose I would like to submit MobileNet in the Offline scenario on an SUT that takes 1 ms per sample. Do I need to iterate ~2.4 times over 24,576 samples (Section 3) or 59 times over 1024 samples (Section 4.1) for a valid performance run?

In this scenario, it is necessary to load 1024 images into DRAM. The LoadGen will select samples uniformly randomly with replacement from the 1024 images. In order to meet the duration minimum and the sample minimum, it is necessary to run one query with 60,000 samples. Since 60,000 is greater than 1024, some samples will be included in the query multiple times. It is possible, that one or more samples will never be selected and will not appear in the query.

> Is it only allowed to process one sample (e.g. image) per query for the SingleStream scenario (Section 3)? Even for an accuracy run (where we need to process e.g. 50,000 images for ImageNet)?

Section 5.1 says:
> For v0.5, the same code must be run for both the accuracy and performance LoadGen modes.

Performance mode for SingleStream specifies one sample per query, so accuracy mode must do the same.

**Comment by tjablin** [comment]
Section 4.1 says:

> For performance runs, the LoadGen will select queries uniformly at random (with replacement) from a test set. The size of the test set for each benchmark is listed as 'QSL Size' in the table above.

The second sentence is kind of misleading without the first sentence.

**Comment by psyhtest** [comment]
Hi Tom, thanks for the explanation. In the heat of the moment, I forgot that queries get selected at random, so it is possible to have more queries than samples. How about modifying Section 4.1 from:
> For performance runs, the LoadGen will select queries uniformly at random (with replacement) from a test set. The size of the test set for each benchmark is listed as 'QSL Size' in the table above.

to:
> For performance runs, the LoadGen will select queries uniformly at random (with replacement) from a test set. The **minimum** size of the test set for each benchmark is listed as 'QSL Size' in the table above. **If the minimum test set size is less than the minimum required query count, some samples will be included in the query multiple times.**

**Comment by psyhtest** [comment]
Now it is clear that this code was wrong:
```
-    parser.add_argument("--queries-offline", type=int, default=24576,
-                        help="mlperf number of queries for Offline")
```
(the default should have been 1; 24576 is the number of samples, not queries)

```
-    parser.add_argument("--queries-multi", type=int, default=24576,
-                        help="mlperf number of queries for MultiStream,Server")
```
(the defaults are model-specific: 270,336 queries for image models and 90,112 otherwise.)

**Comment by psyhtest** [comment]
Are we missing another default?
```
*.SingleStream.samples_per_query = 1
```

**Comment by tjablin** [comment]
Even if the QSL size is greater than the total number of samples, some queries may be selected more than once or not at all.

Section 5.1:
> LoadGen generates queries based on trace. The trace is constructed by uniformly sampling (with replacement) from a library based on a fixed random seed and deterministic generator. The size of the library is listed in as 'QSL Size' in the 'Benchmarks' table above.

**Comment by psyhtest** [comment]
On the other hand, the tail latency percentile is `N/A` for the Offline mode in [Section 3](https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#3-scenarios). Is this superfluous then?
```
*.Offline.target_latency_percentile = 90
```
If 90% is pretty meaningless, why are we clinging to [24,576 samples](https://github.com/mlperf/inference_policies/blob/master/inference_rules.adoc#10-appendix-number-of-queries) then? Running that many samples on an edge device (e.g. MobileNet runs at 4 samples/second on Raspberry Pi 4 with TFLite) will take over an hour, while running even for a couple of minutes at peak performance may lead to thermal throttling.

You can argue offline inference is not a realistic use case for such devices, but it's indicative of ideal throughput. I think MLPerf submitters can be put to a disadvantage, if their competitors publish throughput numbers based on offline inference running for a couple of minutes, rather than a couple of hours.

**Comment by psyhtest** [comment]
> Even if the QSL size is greater than the total number of samples, some queries may be selected more than once or not at all.

Yes, I understand that, but the QSL size is only greater than the required number of samples for GNMT in the SingleStream mode (3003 > 1024), right?

> LoadGen generates queries based on trace. The trace is constructed by uniformly sampling (with replacement) from a library based on a fixed random seed and deterministic generator. The size of the library is listed in as 'QSL Size' in the 'Benchmarks' table above.

Can we replace 'library' with 'test set' here for consistency with the end of Section 3?

**Comment by psyhtest** [comment]
Coming back to the minimum number of samples for each scenario, I'm puzzled this is nowhere to be seen in `mlperf.conf`.

For example, we know that:
```
*.Offline.min_query_count = 1
```
However, we can't set:
```
*.Offline.samples_per_query = 24576
```
as there may be more queries than 1, right (e.g. if the SUT can process no more than 5,000 samples per query due to memory size constraints)?

**Comment by tjablin** [comment]
There's no good justification for the minimum number of samples required for Offline mode other than comity with the other modes. I think an hour long run on the very smallest reasonable device is acceptable. I think it is too late to change the requirements for Offline mode particularly since no one has actually complained about Offline run durations on an SUT they are planning to submit.

**Comment by tjablin** [comment]
Also, the goal for Offline is to measure sustained throughput in the limit, so the run should be long enough to measure thermally throttled performance rather than peak performance.

**Comment by psyhtest** [comment]
I estimate an hour and a half for MobileNet on Rpi4, but it's a comparatively high end dev board. But I agree it's too late to change for this round.

What would you think about updating this requirement for the next round to specify only the minimum duration, say, 60 seconds, rather than both that and the minimum number of samples?

**Comment by tjablin** [comment]
Generally speaking longer runs are better than shorter runs. Until and unless a submitter complains about a SUT taking too long, I am disinclined to reduce or remove the minimum query counts for Offline mode. I am prepared to show more flexibility if a submitter needs it for a planned submission.

**Comment by psyhtest** [comment]
Consider mine a submitter's complaint.

Are we going with the same limits for the Open?

**Comment by tjablin** [comment]
Are you planning to submit a SUT that has overall performance characteristics that are roughly comparable to a Rpi4? Are your offline performance runs more than two hours? If your offline performance runs are pushing the bounds of tolerability, what are you doing about offline accuracy runs which are even longer?

**Comment by psyhtest** [comment]
RPi4 is one of our SUTs. We accept we need almost 4 hours for a full accuracy run. There is just no way around that. It's just we were hoping to get away with a much shorter performance run.

**Comment by tjablin** [comment]
It's none of my business, but why are you planning to submit an RPi4? Are you planning to normalize to RPi4 scale? Do you just want to drop the minimum number of queries for Offline?

**Comment by psyhtest** [comment]
Why not? (to all your questions)

**Comment by christ1ne** [comment]
@psyhtest we can revisit the requirements for the next round. Please file a specific rule change request if needed.
