### ISSUE TITLE
Accuracy data set?

### ISSUE THREAD

**Issue by tjablin** [mlperf/inference_policies#92]
Section 7 says:

> For each benchmark, MLPerf will provide pointers to:
> 
> An accuracy data set, to be used to determine whether a submission meets the quality target, and used as a validation set

We should clarify which dataset is the accuracy dataset.

**Comment by tjablin** [comment]
Also, we should be clear that the 'QSL Size' applies to performance mode only and the accuracy data set size is much larger than 'QSL Size' except for NMT.

**Comment by DilipSequeira** [comment]
Agreed. The current wording is "For performance runs, the LoadGen will select queries uniformly at random (with replacement) from a test set. The size of the test set for each benchmark is listed as 'QSL Size' in the table above.", with nothing about accuracy set size.

**Comment by tjablin** [comment]
Do you want to attempt a fix?

**Comment by christ1ne** [comment]
I will open a PR before the meeting this afternoon on this.

**Comment by tjablin** [comment]
Ping?

**Comment by christ1ne** [comment]
please re-open if needed
