### ISSUE TITLE
Add GNMT sentence length distribution to the repository

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/inference_policies#94]
For the cloud scenario, batching logic wants to predict the marginal latency cost to currently queued queries of waiting for the next inbound request. For the CV benchmarks this can be calculated from just the Poisson rate parameter, but for GNMT the distribution of sequence lengths is also needed.

**Comment by tjablin** [comment]
Addressed in #95. PTAL.

**Comment by nvmbreughe** [comment]
@christ1ne , I assume you are discussing the calibration set I added in https://github.com/mlperf/inference/pull/396 ?

It contains 500 out of the 19188 training samples, so 2.6%.

**Comment by christ1ne** [comment]
Thanks! @nvmbreughe  for the info.
