### ISSUE TITLE
Sorting SSD Images by Image ID in Offline

### ISSUE THREAD

**Issue by tjablin** [mlperf/inference_policies#97]
Do we agree that sorting SSD images by image id is in violation of the anti-coalescing rule? Techniques that only improving performance due to SSD's small QSL size ought to run afoul of the anti-coalescing rule, right?

**Comment by DilipSequeira** [comment]
It's without question against the _spirit_ of the rule. We probably need a prohibition against e.g. "techniques that take advantage of samples being repeated within or across queries", since I don't think this is strictly either coalescing or caching.

**Comment by tjablin** [comment]
By contrast Intel's [PR 484](https://github.com/mlperf/inference/pull/484) is valid because also works for non-identical queries?

**Comment by DilipSequeira** [comment]
I don't think sorting queries by length violates the spirit of the rules. 

Whether it should be untimed, and whether it's reasonable to change the reference model at this stage, are different questions - both concern me.

**Comment by tjablin** [comment]
In Intel's PR, I think the sorting operation is timed. Maybe I misread it? I agree that sorting the input ought to be timed since sorting is not one of the enumerated untimed pre-processing operations.

I also agree that it is too late to change the reference models.

**Comment by tjablin** [comment]
Addressed in #101. PTAL.
