### ISSUE TITLE
minimum list of files needed this Friday.

### ISSUE THREAD

**Issue by christ1ne** [mlperf/inference_policies#99]
Let's decide on the list of files per entry to allow the Closed Division submitter to have the chance to improve the submission package structure (not the performance data).

my proposal:

**Closed Division**
-- log summary per entry
-- log detail per entry
-- accuracy log (at least one per model implemented)
-- code 
-- log compliance checker and its printed error messages
-- human readable results
-- must add <system_desc_id>.json metadata

**Open Division**
-- (same as closed division)

**Comment by DilipSequeira** [comment]
+ self certification questionnaire

**Comment by tjablin** [comment]
WG decides self-cert checklist due by Friday unless you ask for an extension until Wednesday.

**Comment by jveejay** [comment]
Open division requirements are the same as the closed division! See list above.

**Comment by jveejay** [comment]
Updated the closed division to also include system...json data.

**Comment by tjablin** [comment]
WG adopts Christine's proposal. WG decides same for closed and open. WG decides if you do not pass Guenther's compliance check you must file an issue against yourself and fix it. WG decides you also need the system_description_id.json file.
